# Generated by Django 3.0.8 on 2020-08-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='noimage.jpg', upload_to='posts'),
        ),
    ]
